# Generated by Django 2.1.3 on 2019-01-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='attribute',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
