# Generated by Django 2.1.3 on 2019-01-10 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0002_auto_20190107_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIST_survey.Choice')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIST_survey.Respondent')),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='like',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='suggestedchoice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='suggestedchoice',
            name='respondent',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='SuggestedChoice',
        ),
    ]
