# Generated by Django 2.1.3 on 2019-01-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0003_auto_20190110_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_allowed_skip',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_like_required',
            field=models.IntegerField(default=0),
        ),
    ]
