# Generated by Django 2.1.3 on 2019-01-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0004_auto_20190121_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='example_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
