# Generated by Django 2.1.3 on 2019-02-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0007_auto_20190214_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='has_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquete',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
