# Generated by Django 2.1.3 on 2019-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0008_auto_20190218_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='with_answered_num',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='without_select',
            field=models.BooleanField(default=False),
        ),
    ]
