# Generated by Django 2.1.3 on 2019-04-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0009_auto_20190301_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='unique_url',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
