# Generated by Django 2.1.3 on 2019-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0012_auto_20190419_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='term_of_service',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
