# Generated by Django 2.1.3 on 2019-07-19 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0013_enquete_term_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
