# Generated by Django 2.1.3 on 2019-09-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0016_auto_20190731_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='enquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIST_survey.Enquete'),
        ),
    ]
