# Generated by Django 2.1.3 on 2019-10-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0018_question_is_result_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('userid', 'userid'), ('question', 'question'), ('single', 'single'), ('multi', 'multi')], max_length=40),
        ),
    ]
