# Generated by Django 2.1.3 on 2019-08-30 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0019_auto_20191011_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
