# Generated by Django 2.1.3 on 2019-10-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0021_evaluation_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respondent',
            old_name='timestamp',
            new_name='finishTime',
        ),
        migrations.AddField(
            model_name='respondent',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
