# Generated by Django 2.1.3 on 2019-10-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0022_auto_20191004_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='hashedIpAddress',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
