# Generated by Django 2.1.3 on 2020-03-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIST_survey', '0023_respondent_hashedipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='access_token',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='unique_url',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
