version: '3'

services:
  mysql:
    image: mysql:8.0.12
    command: >
      mysqld
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_ja_0900_as_cs
        --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - container.env
  django:
    build: ./django
    depends_on:
      - mysql
    links:
      - mysql
    command: gunicorn config.wsgi -b 0.0.0.0:8000 --reload
    volumes:
      - ./django:/src
      - static-data:/opt/static
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    expose:
      - 8000
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - pma-data:/sessions
    ports:
      - 9000:80
    environment:
      PMA_HOST: mysql
  nginx:
    image: nginx:1.15.10
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/log:/var/log/nginx
      - static-data:/app/static
    depends_on:
      - django

volumes:
  mysql-data:
  pma-data:
  static-data:
  yarn-cache:
